"""empty message

Revision ID: 42424a11ef9f
Revises: 57d4e6b53b14
Create Date: 2021-09-18 03:19:22.391949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42424a11ef9f'
down_revision = '57d4e6b53b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('types', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='category_pkey')
    )
    # ### end Alembic commands ###
